import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  {
    name: 'Jasmine Rice - 5kg',
    slug: toSlug('Jasmine Rice - 5kg'),
    category: 'Rice & Grains',
    images: ['/images/jasmine-rice.jpg'],
    tags: ['best-seller', 'fragrant'],
    isPublished: true,
    price: 14.99,
    listPrice: 16.99,
    brand: 'Thai Premium',
    avgRating: 4.8,
    numReviews: 40,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 10 },
      { rating: 5, count: 22 },
    ],
    numSales: 120,
    countInStock: 60,
    description:
      'Premium Thai Jasmine rice, known for its aromatic fragrance and fluffy texture.',
    sizes: ['5kg', '10kg'],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Biryani Basmati Rice - 10kg',
    slug: toSlug('Biryani Basmati Rice - 10kg'),
    category: 'Rice & Grains',
    images: ['/images/basmati-rice.jpg'],
    tags: ['long-grain', 'best-for-biryani'],
    isPublished: true,
    price: 22.99,
    listPrice: 25.99,
    brand: 'Royal Basmati',
    avgRating: 4.7,
    numReviews: 35,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 8 },
      { rating: 5, count: 22 },
    ],
    numSales: 95,
    countInStock: 45,
    description: 'Long-grain basmati rice, perfect for biryanis and pulao.',
    sizes: ['5kg', '10kg'],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Masoor Dal (Red Lentils) - 1kg',
    slug: toSlug('Masoor Dal - 1kg'),
    category: 'Pulses & Lentils',
    images: ['/images/masoor-dal.jpg'],
    tags: ['protein-rich', 'healthy'],
    isPublished: true,
    price: 3.99,
    listPrice: 4.49,
    brand: 'Desi Fresh',
    avgRating: 4.6,
    numReviews: 20,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 11 },
    ],
    numSales: 85,
    countInStock: 30,
    description: 'High-quality red lentils, perfect for dals and curries.',
    sizes: ['1kg', '2kg'],
    colors: ['Red'],
    reviews: [],
  },
  {
    name: 'Chana Dal (Split Chickpeas) - 1kg',
    slug: toSlug('Chana Dal - 1kg'),
    category: 'Pulses & Lentils',
    images: ['/images/chana-dal.jpg'],
    tags: ['fiber-rich', 'best-for-curry'],
    isPublished: true,
    price: 4.29,
    listPrice: 5.0,
    brand: 'Healthy Choice',
    avgRating: 4.7,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 14 },
    ],
    numSales: 90,
    countInStock: 40,
    description:
      'Premium chana dal, great for making traditional Indian dishes.',
    sizes: ['1kg', '2kg'],
    colors: ['Yellow'],
    reviews: [],
  },
  {
    name: 'Soya Sauce - 500ml',
    slug: toSlug('Soya Sauce - 500ml'),
    category: 'Condiments & Sauces',
    images: ['/images/soya-sauce.jpg'],
    tags: ['best-seller', 'asian-cuisine'],
    isPublished: true,
    price: 2.99,
    listPrice: 3.49,
    brand: 'Kikkoman',
    avgRating: 4.8,
    numReviews: 30,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 7 },
      { rating: 5, count: 20 },
    ],
    numSales: 100,
    countInStock: 50,
    description: 'Authentic soy sauce for Asian-style cooking.',
    sizes: ['500ml', '1L'],
    colors: ['Dark Brown'],
    reviews: [],
  },
  {
    name: 'Green Tea - 100 Bags',
    slug: toSlug('Green Tea - 100 Bags'),
    category: 'Beverages',
    images: ['/images/green-tea.jpg'],
    tags: ['antioxidant-rich', 'best-seller'],
    isPublished: true,
    price: 5.49,
    listPrice: 6.49,
    brand: 'Lipton',
    avgRating: 4.7,
    numReviews: 50,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 5 },
      { rating: 4, count: 10 },
      { rating: 5, count: 34 },
    ],
    numSales: 200,
    countInStock: 80,
    description:
      'Premium green tea with a refreshing taste and high antioxidants.',
    sizes: ['100 Bags'],
    colors: ['Green'],
    reviews: [],
  },
  {
    name: 'Fresh Paneer - 250g',
    slug: toSlug('Fresh Paneer - 250g'),
    category: 'Dairy',
    images: ['/images/paneer.jpg'],
    tags: ['protein-rich', 'best-for-cooking'],
    isPublished: true,
    price: 3.99,
    listPrice: 4.49,
    brand: 'Amul',
    avgRating: 4.8,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 12 },
    ],
    numSales: 120,
    countInStock: 45,
    description:
      'Freshly made paneer, ideal for Indian dishes like Paneer Butter Masala.',
    sizes: ['250g', '500g'],
    colors: ['White'],
    reviews: [],
  },
]

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Farm-Fresh Goodness Delivered to Your Doorstep!',

      buttonCaption: 'Shop Now',

      image: '/images/banner1.jpg',

      url: '/search?category=Shoes',

      isPublished: true,
    },
    {
      title: 'Tasty Treats, Anytime! ',

      buttonCaption: 'Shop Now',

      image: '/images/banner2.jpg',

      url: '/search?category=T-Shirts',

      isPublished: true,
    },
    {
      title: 'From Bold to Natural – We’ve Got Your Perfect Shade!',

      buttonCaption: 'See More',

      image: '/images/banner3.jpg',

      url: '/search?category=Wrist Watches',

      isPublished: true,
    },
  ],
}
export default data
